### ISSUE TITLE
Not working on ubuntu 22.04 jammy

### ISSUE THREAD

**Issue by Logicwax** [saivert/ddb_output_pulse2#5]
Currently this plugin does not work with latest deadbeef on ubuntu 22.04 (jammy)

**Comment by saivert** [comment]
A backtrace if it crashes or some logs would help.

I don't have time to fire up a Ubuntu 22.04 installation to test. This plugin has worked on every Ubuntu version in the past 4 years so I find this highly surprising. But maybe Canonical has changed something again.

**Comment by Logicwax** [comment]
I just tried to test this again in order to get you some logs, and now its working great!   Weird.  must have been some recent ubuntu update that fixed it.    I just had to change the buffer to something like 1 or 5ms (instead of 512 that was in there) to get the UI to update nicely (I messed with that before, and it made no difference; the plugin still refused to work).

Closing this for now.   Thanks for the hard work on this!
